### ISSUE TITLE
Port modules from AlexVCaron/nf-scil

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/nf-neuro#14]
- [x] AlexVCaron/nf-neuro#1 @ThoumyreStanislas 
- [x] AlexVCaron/nf-neuro#2 @Manonedde 
- [x] AlexVCaron/nf-neuro#3 @gagnonanthony 
- [x] AlexVCaron/nf-neuro#4 @arnaudbore 
- [x] AlexVCaron/nf-neuro#5 @ThoumyreStanislas 
- [x] AlexVCaron/nf-neuro#6 @Manonedde 
- [x] AlexVCaron/nf-neuro#7 @gagnonanthony 
- [x] AlexVCaron/nf-neuro#8 @arnaudbore

**Comment by AlexVCaron** [comment]
I'll start here. This is how I intend to do it, so it is quick for everyone :

- I'll rerun all tests to make sure all branches are up-to-date with test data
- I'll re-lint, prettier and editorconfig everything
- We create PRs and assign them to the team

What do you think @arnaudbore ?

**Comment by arnaudbore** [comment]
Reference PR: https://github.com/scilus/nf-scil/pull/177
