### ISSUE TITLE
Port subworkflows from AlexVCaron/nf-scil

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/nf-neuro#15]
- [x] AlexVCaron/nf-neuro#9
- [x] AlexVCaron/nf-neuro#10
- [x] AlexVCaron/nf-neuro#11
- [x] AlexVCaron/nf-neuro#12
